DROP ALL OBJECTS;

CREATE TABLE TAXNUM (
  TSN CHAR(6) PRIMARY KEY NOT NULL
, NAME VARCHAR(255) NOT NULL
, "TYPE" VARCHAR(255) NOT NULL
, PARENT CHAR(6)
);

INSERT INTO TAXNUM SELECT * FROM CSVREAD('taxnum.csv');

CREATE INDEX TAXNUM_ON_PARENT ON TAXNUM(PARENT);